### ISSUE TITLE
"Jobs added with no trigger must be durable" after update to 3.15.1

### ISSUE THREAD

**Issue by Trapulo** [quartznet/quartznet#2791]
**Describe the bug**

After upgrade from 3.15.0 to 3.15.1 I have the error "Jobs added with no trigger must be durable".

**Version used**

3.15.1

**To Reproduce**

    var jobKey = new JobKey(nameof(DailyRecalculateJob));
    q.AddJob<DailyRecalculateJob>(opts => opts.WithIdentity(jobKey));

    string cronSchedule = builder.Environment.IsProduction() ? "0 11 1 ? * * *" : "0 * * * * ?";  // Once day in production, Every 1 minutes in development

    q.AddTrigger(opts => opts
        .ForJob(jobKey)
        .WithIdentity("DailyRecalculateJob-trigger", "cdr")
        .WithCronSchedule(cronSchedule));

  builder.Services.AddQuartzServer(options =>
  {
      options.WaitForJobsToComplete = true;
  });

**Additional context**

With 3.15.0 it works

**Comment by bdovaz** [comment]
@lahma I'll respond here for this issue and this other one https://github.com/quartznet/quartznet/issues/2793.

When I created the PR https://github.com/quartznet/quartznet/pull/2787, the tests passed, and I ran the sample project `Quartz.Examples.AspNetCore`.I don't know what's going on because in that sample project you can see how the jobs are running.

If you can, @Trapulo or @nomz0101, please send us a complete minimum project where it can be reproduced. I would appreciate it.

**Edit:** @lahma I have created a PR (https://github.com/quartznet/quartznet/pull/2794) adding tests for all overloads to make it clear that it is working correctly at that point.

**Comment by nomz0101** [comment]
@lahma @bdovaz 
I've identified the root cause for my issue (https://github.com/quartznet/quartznet/issues/2793) on my end. 
It appears there may have been a timing change in how triggers are registered. I had logic that was dependent on the AddTrigger event firing synchronously/immediately, but when I removed that dependency, the trigger fired successfully at a later point in the lifecycle.

This suggests the trigger registration may now occur asynchronously or at a different stage in the initialization process, possibly due to dependency injection configuration changes.

The issue is resolved on my side by adjusting my code to not rely on immediate trigger registration. 
Thank you for looking into this issue.

**Comment by lahma** [comment]
Considering this as duplicate so please create a repro and we can reopen if still a problem.

**Comment by Trapulo** [comment]
@lahma  I cannot find a way to fix as @nomz0101 

this is my startup (in ASP.NET CORE as https://www.quartz-scheduler.net/documentation/quartz-3.x/packages/aspnet-core-integration.html#a-practical-example-of-the-setup)

```
 builder.Services.AddQuartz(q =>
 {
     var jobKey = new JobKey(nameof(DailyRecalculateJob));
     q.AddJob<DailyRecalculateJob>(opts => opts.WithIdentity(jobKey));

     string cronSchedule = builder.Environment.IsProduction() ? "0 11 1 ? * * *" : "0 * * * * ?";  // Once day in production, Every 1 minutes in development
     q.AddTrigger(opts => opts
         .ForJob(jobKey)
         .WithIdentity("DailyRecalculateJob-trigger", "cdr")
         .WithCronSchedule(cronSchedule));
 });

 builder.Services.AddQuartzHostedService(options =>
 {
     // when shutting down we want jobs to complete gracefully
     options.WaitForJobsToComplete = true;
 });

```

than later in    app.Run(); I have the runtime error.
