### ISSUE TITLE
Concurrent jobs are fired even though clustrered and DisallowConcurrentExecution

### ISSUE THREAD

**Issue by nhh-softwarehuset** [quartznet/quartznet#456]
Setup: Clustered SQL Database
Job: Triggers every 5 seconds. Takes 10 seconds to execute. SimpleScheduler

The job will start efter 5 seconds on multiple other hosts even though it is set to disallowConcurrentExcecution. We have tried adding IgnoreMisfire without solving the issue.

The testapp can be found here. The scheduler seem to spawn a new job even though it is still blocked at database level
https://github.com/nhh-softwarehuset/quartznet

We are seeing an issue. probably because of a configuration issue or a missunderstanding about what Quartz are capable of.

**Comment by mdecima** [comment]
I have a similar problem, first it was that the nodes were with different time, but that already was corrected

**Comment by nhh-softwarehuset** [comment]
@mdecima @lahma  Just an input. We MAY have found a solution to this issue. Hope this guide makes sense :)

Simple Trigger:
Set StartAt a couple of minutes into the future: "StartAt(DateTime.Now.AddMinutes(2))"
In the meantime the application will sync with the cluster and all instances can get started without taking the job because.
instance 1. Starts at 12:00. Schedule the task to be at 12:02
instance 2. Starts at 12:01. Schedule the task to be at 12:03
instance 3. Starts at 12:02 Schedule the task to be at 12:04

This way no one of the instances starts the task before every single instance are up and running. You are now sure that the tasks will not start on startup and spawn new jobs.

**Comment by lahma** [comment]
Have you tried setting AcquireTriggersWithinLock to true in configuration for job store?

**Comment by johnradke** [comment]
I believe we are running into this as well using clustered setup with Oracle.ManagedDataAccess on Oracle 11g. It happens relatively rarely (given the volume of jobs), but the partial timeline is (assuming a Quartz service running on servers Alpha and Beta):
1. Alpha: queries for next trigger, gets trigger Foo (which has NEXT_FIRE_TIME of X)
2. Alpha: gets trigger info
3. Beta: queries for next trigger, gets trigger Foo (which *still* has NEXT_FIRE_TIME of X)
4. Beta: gets trigger info
5. Beta: updates STATE of trigger Foo to ACQUIRED
6. Beta: inserts FIRED_TRIGGER record
7. Beta: acquires lock TRIGGER_ACCESS
8. Beta: updates FIRED_TRIGGER record to state of EXECUTING
9. **Beta: updates trigger Foo with new NextFireTime and back to state of WAITING**
10. **Alpha: updates STATE of trigger Foo to ACQUIRED**
11. Beta: returns lock TRIGGER_ACCESS
12. Beta: executes job
(etc.)

Running with `AcquireTriggersWithinLock = true` should fix this. But it seems to me that this could happen in any clustered setup, and therefore that `AcquireTriggersWithinLock` should always be `true` when Clustered is `true`.

Alternatively, here's the code which updates the trigger's state to ACQUIRED (nos. 5 and 10 in the list above):
https://github.com/quartznet/quartznet/blob/139aafa23728892b0a5ebf845ce28c3bfdb0bfe8/src/Quartz/Impl/AdoJobStore/JobStoreSupport.cs#L2651-L2656

Currently this ensures that the trigger's state is at WAITING, and if not, we move on to the next trigger. This could be updated to *also* check that the trigger's NextFireTime has not changed since `RetrieveTrigger` was called (nos. 2 and 4 above) earlier in that method.

**Comment by lahma** [comment]
I think there have been various fixes since since the referenced version. If still reproduces with 3.1 beta 2 or later we can reopen.
